### PR TITLE
Fix typo in the readme

### PR DESCRIPTION
**Pull request by gray-adeyi**
Hi nimase80. Just about to try you project when i caught a typo in the readme 'develope' instead of 'develop'. No offense.

### CODE REVIEW

**Comment by nimaes80** [comment]
Thanks.

**Comment by gray-adeyi** [comment]
Thanks for merging my pr even though it's a simple one. I couldn't find an English documentation. Can you help me with that?

**Comment by nimaes80** [comment]
Unfortunately, I did not write the document in other languages, but I wrote the Persian document in fluent Farsi, so you can translate it into your local language using Google Translate. In the case of English, I tested it and there was no translation problem.

**Comment by gray-adeyi** [comment]
Thanks. so you're saying i should copy the text in the documentation into google translate? doing that

**Comment by nimaes80** [comment]
Don't need to copy text line by line, in chrome browser there is an option to translate whole page.

**Comment by gray-adeyi** [comment]
Okay, thanks for your help

**Pull request merged**
